import shelve

from selenium import webdriver  # Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from web.podemo1.page import add_member_page
from web.podemo1.page.add_member_page import AddMemberPage


class Mainpage:
    def __init__(self):
        options = Options()
        options.debugger_address = "127.0.0.1:9222"
        self.driver = webdriver.Chrome(options=options)

    def goto_addmember(self):
        self.driver.find_element(By.CSS_SELECTOR,".index_service_cnt_itemWrap")
        return AddMemberPage(self.driver)
